<body class="bg-dark text-white">
<div class="bg-dark text-white">
<form method="POST" action="index/search">
    <div class="input-group rounded  bg-secondary">
    <input type="search" class="form-control rounded m-5"
     name="search1" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
    </div>
    <div class="row">
    <div class="form-check m-5">
        <input class="form-check-input" name="artist" type="checkbox" value="artist" id="flexCheckDefault">
        <label class="form-check-label" for="flexCheckDefault">
            Artist
        </label>

    </div>
    <div class="form-check m-5 ">
        <input class="form-check-input " name="playlist" type="checkbox" value="playlist" id="flexCheckDefault">
        <label class="form-check-label" for="flexCheckDefault">
            Playlist
        </label>

    </div>
    <div class="form-check m-5">
        <input class="form-check-input" name="episode" type="checkbox" value="episode" id="flexCheckDefault">
        <label class="form-check-label" for="flexCheckDefault">
            Episode
        </label>

    </div>
    <div class="form-check m-5">
        <input class="form-check-input" name="album" type="checkbox" value="album" id="flexCheckDefault">
        <label class="form-check-label" for="flexCheckDefault">
            Album
        </label>

    </div>
    <div class="form-check m-5">
        <input class="form-check-input" name="show" type="checkbox" value="show" id="flexCheckDefault">
        <label class="form-check-label" for="flexCheckDefault">
            Show
        </label>

    </div>
    <div class="form-check m-5 ">
        <input class="form-check-input" name="track" type="checkbox" value="track" id="flexCheckDefault">
        <label class="form-check-label" for="flexCheckDefault">
            Track
        </label>

    </div>
    </div>
<center><button type="submit" class="align-center"><i class="fas fa-search m-1 "></i>Search</button></center>
</form>
</div>
</body>